---
title: "HW10: Data Visualization II"
author: "Andrea Winingar"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

load Packages chunk.

```{r}
library(tidyverse)
library(here)
library(GGally)
```

### Import and Wrangle

import sparrows

```{r}
sparrow_raw <- read_tsv(here('data','sparrows.txt'))
```

Add columns box_group and row_order

```{r}
sparrows <- sparrow_raw %>% 
  mutate(box_group = "Sparrows",
         row_order = 1:nrow(.))
```

### Figure 2: outliers

Create boxplot on left of figure 2.

```{r}
plot_box <- sparrows %>% 
  ggplot(aes(x = box_group, 
             y = wingcrd)) +
  geom_boxplot(width = 0.25) +
  labs(x = NULL,
       y = "Wing length (mm)")
```

Create cleveland plot on right side of figure 2.

```{r}
plot_cleveland <- sparrows %>% 
  ggplot(aes(x = wingcrd,
             y = row_order)) +
  geom_point() +
  labs(x = "Wing length (mm)",
       y = "Order of the data")
```

### Figure 3: otliers

make the six chunks of code in figure 3 in one code chunk.

```{r}
p_culmen <- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = culmen)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_nalospi<- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = nalospi)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_wt<- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = wt)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_wingcrd<- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = wingcrd)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_tarsus<- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = tarsus)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_head<- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = head)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

Nalospi, tarsus, and head have outliers.






