---
title: "HW13: Strings and Things"
author: "Andrea Winingar"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Load packages.

```{r}
library(tidyverse)
library(here)
library(ggthemes)
library(gghighlight)
```

### Part 1: DNA Strings

#### Import the Data

```{r}
beta_import <- read_lines(here('data', 'beta_gliadin.txt'), skip = 1)
print(beta_import)
```

#### From many Strings to One

Replace all whitespaces and digits with nothing. 

```{r}
beta_replaced <- beta_import %>% 
  str_replace_all("\\s", "") %>% 
  str_replace_all("\\d", "") %>% 
  str_c(collapse = "") %>% 
  str_to_upper()
beta_replaced
str_length(beta_replaced)
```

#### Sequence analysis: find the promoter region

Find how many possible start and stop codons.

```{r}
str_count(beta_replaced, "[^ACTG]")
str_count(beta_replaced, 'ATG')
str_count(beta_replaced, 'TGA|TAA')
```

Create caat_box and tata_box, count how many times they occur

```{r}
caat_box <- "CCAAT"
tata_box <- "CTATAA"
str_count(beta_replaced, caat_box)
str_count(beta_replaced, tata_box)
```

Create caat_seq anda tata_seq then count them.

```{r}
caat_seq <- "CCAAT.{100,150}ATG"
str_count(beta_replaced, caat_seq)
tata_seq <- "CTATAA.{50,100}ATG"
str_count(beta_replaced, tata_seq)
```

Find out if any caat_seq have tata_seq

```{r}
caat_seqs_all <- beta_replaced %>% 
  str_extract_all(caat_seq, simplify = TRUE)
str_which(caat_seqs_all, tata_seq)
promoter <- str_sub(caat_seqs_all[1])
promoter
str_length(promoter)
```











